### PR TITLE
Include hpack in the hpack dir output

### PR DESCRIPTION
**Pull request by NorfairKing**
Fix for #448

### CODE REVIEW

**Review by sandydoo — APPROVED** [review]
This'll work 👍 I suppose `symlinkJoin` is also an option.

We now have [`extraPackages`](https://github.com/cachix/git-hooks.nix/blob/fa606cccd7b0ccebe2880051208e4a0f61bfc8c1/modules/hooks.nix#L1352-L1355) to accomplish this. But...since we don't have an easy way to override `hpack`, I think it would be deceiving to use it until we first untangle `tools`.

**Comment by NorfairKing** [comment]
@sandydoo would you prefer the `extraPackages` approach? I guess I do care about overriding but not that much..

**Comment by sandydoo** [comment]
> @sandydoo would you prefer the `extraPackages` approach? I guess I do care about overriding but not that much..

@NorfairKing, sure

**Comment by NorfairKing** [comment]
@sandydoo I'm thinking about it again and making overriding `hpack` possible is actually pretty important in hindsight. Otherwise there's just no way to do it.

I'm open to nicer approaches though.

**Comment by NorfairKing** [comment]
@sandydoo Thanks! I'd be happy to help maintain this hook in case we run into trouble because of this.

**Pull request merged**
