### PR TITLE
Add support for TruffleHog

### PR DESCRIPTION
**Pull request by therealpxc**
This adds support for the [TruffleHog](https://github.com/trufflesecurity/trufflehog) secrets scanner. It's presently not nearly as configurable as I'd like, or as neat as I'd like, but hopefully I can take it out of WIP status soon. :)

### CODE REVIEW

**Comment by therealpxc** [comment]
I think I'd like to push this as-is now, and add configurability for individual TruffleHog options at a later time, after feedback from users

**Comment by sandydoo** [comment]
Lets remove the commented out entry. Otherwise, LGTM!

**Comment by therealpxc** [comment]
Oops! Of course. Done. :)

**Comment by therealpxc** [comment]
@sandydoo I believe this is ready! :)

**Pull request merged**
