### PR TITLE
Add yamlfmt

### PR DESCRIPTION
**Pull request by bryanhonof**
Add support for [yamlfmt].
I mostly copy/pasted from yamllint.
So, it might be incomplete, but it seems to be doing what I expect it to do.

[yamlfmt]: https://github.com/google/yamlfmt

### CODE REVIEW

**Comment by domenkozar** [comment]
You you rebase?

**Comment by domenkozar** [comment]
ping

**Comment by domenkozar** [comment]
```
error: builder for '/nix/store/z81000y8iafhgyq3d0z4cgafckmi64sq-pre-commit-hook-ensure-sops-1.1.drv' failed with exit code 1;
       last 10 log lines:
       > wrapping `/nix/store/g00s2qmmmwq4ha7w01qsfangnv6cj539-pre-commit-hook-ensure-sops-1.1/bin/pre-commit-hook-ensure-sops'...
       > Executing pythonRemoveTestsDir
       > Finished executing pythonRemoveTestsDir
       > running install tests
       > Traceback (most recent call last):
       >   File "/nix/store/g00s2qmmmwq4ha7w01qsfangnv6cj539-pre-commit-hook-ensure-sops-1.1/bin/.pre-commit-hook-ensure-sops-wrapped", line 6, in <module>
       >     from pre_commit_hook_ensure_sops.__main__ import main
       >   File "/nix/store/g00s2qmmmwq4ha7w01qsfangnv6cj539-pre-commit-hook-ensure-sops-1.1/lib/python3.10/site-packages/pre_commit_hook_ensure_sops/__main__.py", line 7, in <module>
       >     from ruamel.yaml import YAML
       > ModuleNotFoundError: No module named 'ruamel.yaml'
       For full logs, run 'nix log /nix/store/z81000y8iafhgyq3d0z4cgafckmi64sq-pre-commit-hook-ensure-sops-1.1.drv'.
```

**Comment by bryanhonof** [comment]
Tried fixing it locally, but then I started to run into some weird errors with OCaml and macOS codesign.
Shelving this for now.

**Comment by bryanhonof** [comment]
Closing in favor of #453

**Pull request closed without merging**
